---
- name: Creating Rclone configureation folder.
  file:
    dest: '/etc/rclone'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  when:
    - mysql_backupset_arg.cloud_rsync | bool
    - mysql_backupset_arg.cloud_drive is defined

- name: Rclone configuration file transfer.
  template:
    src: 'rclone.conf.j2'
    dest: '/etc/rclone/mysql.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when:
    - mysql_backupset_arg.cloud_rsync | bool
    - mysql_backupset_arg.cloud_drive is defined

- name : MySQL backup job.
  cron:
    user: 'mysql'
    name: 'MySQL backup'
    minute: "{{ 60 | random(seed=inventory_hostname) }}"
    hour: "{{ 6 | random(seed=inventory_hostname,step=1) }}"
    job: '/bin/sh /usr/local/bin/innobackupex-runner.sh'
