---
- name: Check if unused configure file exists
  stat: 
    path: '{{ item }}'
  loop:
    - '/etc/logrotate.d/mysql'
  register: file_exists

- name: Remove unused configure file
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - '/etc/logrotate.d/mysql'
  when: file_exists.results[0].stat.exists

- name: Creating MySQL folder
  file:
    dest: '{{ item }}'
    state: directory
    owner: mysql
    group: mysql
    mode: 0755
  loop: '{{ mysql_folder }}'

- name: Configure kernel parameters
  sysctl:
    name: '{{ item.variable }}'
    value: '{{ item.value }}'
    state: present
    reload: yes
    sysctl_set: yes
    sysctl_file: /etc/sysctl.d/20-sysctl.conf
  loop: '{{ mysql_kernel_parameters }}'

- name: MySQL Configure & Scripts file transfer
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: mysql
    group: mysql
    mode: 0664
  loop: '{{ mysql_conf_scripts }}'

- name: Initializes the MySQL 5.7 system tables
  shell: '/usr/sbin/mysqld --defaults-file=/etc/my.cnf --datadir={{ mysql_path }}/mysql --user=mysql --explicit_defaults_for_timestamp --initialize-insecure --ignore-db-dir=prometheus.cnf --ignore-db-dir=mysql-log-rotate'
  when: mysql_version == '57'

- name: Changing Limits for MySQL services
  lineinfile:
    dest: /etc/security/limits.conf
    line: "{{ item.line }}"
  loop:
    - { line: '{{ mysql_user }} soft nofile {{ mysql_arg.open_files_limit }}' }
    - { line: '{{ mysql_user }} hard nofile {{ mysql_arg.open_files_limit }}' }
    - { line: '{{ mysql_user }} soft nproc {{ mysql_arg.open_nproc_limit }}' }
    - { line: '{{ mysql_user }} hard nproc {{ mysql_arg.open_nproc_limit }}' }
    - { line: '{{ mysql_user }} hard memlock unlimited' }
    - { line: '{{ mysql_user }} soft memlock unlimited' }

- name: Changing Limits for MySQL services
  lineinfile:
    state: present
    dest: '/lib/systemd/system/mysqld.service'
    insertafter: '^\[Service\]'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  loop: '{{ mysql_service_parameter }}'
  when: ansible_distribution_major_version|int > 6

- name: Ensure MySQL service is enabled
  systemd:
    name: 'mysqld.service'
    enabled: yes
    state: started
    daemon_reload: yes
  when: ansible_distribution_major_version|int > 6

- name: Ensure MySQL service is enabled
  service:
    name: 'mysql'
    enabled: yes
    state: started
  when: ansible_distribution_major_version|int < 7
