---
- name: Add MySQL YUM repositories
  yum_repository:
    name: '{{ mysql_repo_name }}'
    description: '{{ mysql_repo_name }} YUM repository'
    file: '{{ mysql_repo_name }}'
    baseurl: '{{ mysql_repo_url }}'
    gpgcheck: no

- name: Install the MySQL packages
  yum:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - '{{ mysql_packages }}'

- name: Ensure MySQL firewall port is allow
  firewalld:
    port: '{{ item }}'
    permanent: 'true'
    state: 'enabled'
  with_items:
    - '{{ mysql_port }}'
  when:
    - ansible_distribution_major_version|int > 6
  register: result

- name: Reload firewalld service
  service:
    name: firewalld
    state: reloaded
  when:
    - result|changed
    - ansible_distribution_major_version|int > 6
