---
- name: Prometheus user password generator
  set_fact:
    mysqld_exporter_user_passwd: "{{ lookup('password', '' + group_names[-1] + ':prometheus length=12 chars=ascii_letters,digits') }}"
  no_log: true

- name: Create user prometheus with privileges
  mysql_user:
    login_user: 'root'
    login_password: ''
    login_unix_socket: '{{ mysql_path }}/mysql/mysql.sock'
    name: 'prometheus'
    password: '{{ mysqld_exporter_user_passwd }}'
    host: '127.0.0.1'
    priv: '*.*:PROCESS,REPLICATION CLIENT,REPLICATION SLAVE,SELECT'
    state: 'present'
  no_log: true

- name: Modify root password
  mysql_user:
    login_user: 'root'
    login_password: ''
    login_unix_socket: '{{ mysql_path }}/mysql/mysql.sock'
    name: 'root'
    host: '{{ item }}'
    password: '{{ mysql_sa_pass }}'
    priv: '*.*:ALL,GRANT'
    state: 'present'
  loop:
    - '127.0.0.1'
    - 'localhost'
  no_log: true
